services:
  emg-model:
    build:
      context: .
      dockerfile: Dockerfile
    image: emg-model:latest
    container_name: emg-container
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    tty: true
    stdin_open: true
    # By default start a bash shell so user can run interactive commands
    command: ["bash"]
