services:
  emg-model:
    build:
      context: .
      dockerfile: Dockerfile
    image: emg-model:latest
    container_name: emg-container
    volumes:
      - .:/app
    tty: true
    stdin_open: true
